<?php

namespace instance12
{
	$npcinfo_instance12 = array
	(
		21 => array
			(
			'mode' => 2,
			'num' => 1,
			'pass' => 'wei42bg',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 250,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'r',
			'pls' => 34,
			'mhp' => 12900,
			'msp' => 800,
			'att' => 4000,
			'def' => 4000,
			'lvl' => 65,
			'skill' => 800,
			'money' => 40000,
			'arb' => '武神战甲B',
			'arbk' => 'DB',
			'arbe' => 3000,
			'arbs' => 300,
			'arbsk' => 'A',
			'arh' => '武神战甲H',
			'arhk' => 'DH',
			'arhe' => 2000,
			'arhs' => 300,
			'arhsk' => 'b',
			'arf' => '武神战甲F',
			'arfk' => 'DF',
			'arfe' => 2000,
			'arfs' => 300,
			'arfsk' => 'a',
			'ara' => '武神战甲A',
			'arak' => 'DA',
			'arae' => 2000,
			'aras' => 300,
			'arask' => 'H',
			'art' => '武神之魂',
			'artk' => 'A',
			'arte' => 9,
			'arts' => 9,
			'artsk' => 'ch',
			'sub' => array
			(
				0 => array
				(
					'name' => '黑熊',
					'gd' => 'm',
					'icon' => 210,
					'club' => 18,
					'mhp' => 8932,
					'att' => 5120,
					'skill' => 1919,
					'skills' => array('400'=>'5','401'=>'5','402'=>'1','403'=>'5','461'=>'1','422'=>'0'),
					'wep' => 'Solidarity',
					'wepk' => 'WG',
					'wepe' => 3000,
					'weps' => 3000,
					'wepsk' => 'Nnrd',
					'arb' => 'NATO',
					'arbk' => 'DB',
					'arbe' => 2333,
					'arbs' => 300,
					'arbsk' => 'ZA',
					'arh' => 'Voice of America',
					'arhk' => 'DH',
					'arhe' => 2333,
					'arhs' => 300,
					'arhsk' => 'ZB',
					'arf' => 'One small step',
					'arfk' => 'DF',
					'arfe' => 2333,
					'arfs' => 300,
					'arfsk' => 'Za',
					'ara' => 'Tear down this WALL',
					'arak' => 'DA',
					'arae' => 2333,
					'aras' => 300,
					'arask' => 'ZH',
					'art' => 'Bear Trap',
					'artk' => 'A',
					'arte' => 1,
					'arts' => 1,
					'artsk' => 'Zch',
					'itm1' => '『黑熊刀』',
					'itmk1' => 'WK',
					'itme1' => 90,
					'itms1' => 350,
					'itmsk1' => 'Nnrd',
					'itm2' => '超重型黑熊列车 古斯塔夫最大炮',
					'itmk2' => 'WG',
					'itme2' => 3000,
					'itms2' => 3000,
					'itmsk2' => 'Nnrd',
					'itm3' => '《黑熊语录》',
					'itmk3' => 'VV',
					'itme3' => 153,
					'itms3' => 1,
					'itmsk3' => 'Z',
					'itm4' => '『G.A.M.E.O.V.E.R』',
					'itmk4' => 'Y',
					'itme4' => 1,
					'itms4' => 1,
					'description' => '武神 黑熊，<span class="yellow b">旧英灵四天王之首，被称为英灵殿唯一的良心。（咦？）<br>附带很不要脸的<span class="red b">【直死1】</span>和<span class="red b">【暴风】</span>技能</span>',
				),
			),
		),//END OF TYPE 21
	);//END OF $npcinfo
}
?>