<?php

namespace instance11
{
	$npcinfo_instance11 = array
	( 
		9 => array
		(
			'mode' => 3,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 99,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 103,
			'mhp' => 3000000,
			'msp' => 4000,
			'att' => 200000,
			'def' => 4000,
			'lvl' => 97,
			'skill' => 2400,
			'money' => 1,
			'arb' => '蓝色睡衣',
			'arbk' => 'DB',
			'arbe' => 60,
			'arbs' => 15,
			'arh' => '奥术战甲H - 霜',
			'arhk' => 'DHS',
			'arhe' => 4000,
			'arhs' => 300,
			'arf' => '泡泡拖鞋',
			'arfk' => 'DF',
			'arfe' => 40,
			'arfs' => 15,
			'ara' => '奥术战甲A - 霜',
			'arak' => 'DAS',
			'arae' => 4000,
			'aras' => 300,
			'art' => '龙虎徽标',
			'artk' => 'A',
			'arte' => 200,
			'arts' => 300,
			'artsk' => 'Hc',
			'sub' => array
			(
				0 => array
				(
					'name' => '蓝凝 MUDDY',
					'mss' => 40,
					'skills' => array('406'=>'0','432'=>'0','459'=>'0','461'=>'0'),
					'icon' => 52,
					'wep' => '『AZURE RONDO』',
					'wepk' => 'WKF',
					'wepe' => 2000,
					'weps' => 360,
					'wepsk' => 'rkd',
					'itm1' => '挑战者之证',
					'itmk1' => 'Y',
					'itme1' => 1,
					'itms1' => 1,
					'itm2' => '琉璃血',
					'itmk2' => 'Y',
					'itme2' => 1,
					'itms2' => 1,
					'itm3' => '好想按这个按钮',
					'itmk3' => 'Y',
					'itme3' => 1,
					'itms3' => 1,
					'ext_armor' => array(//需要外甲模块才能生效
						'arb' => '奥术战甲B - 霜',
						'arbk' => 'DBS',
						'arbe' => 6000,
						'arbs' => 400,
						'arbsk' => 'Aa',
						'arf' => '奥术战甲F - 霜',
						'arfk' => 'DFS',
						'arfe' => 4000,
						'arfs' => 300,
						'arfsk' => 'Aa',
					),
					'description' => '坐镇于冰封墓场的NPC，几乎无敌的存在。<span class="yellow b">没事还是不要惹她好了……</span>',
				),
			),
		),//END OF TYPE 9
	);//END OF $npcinfo
}
?>