<?php

namespace skill983
{
	$skill983_npc = array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'club' => 17,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 3,
		'tactic' => 2,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'f',
		'pls' => 201,
		'mhp' => 307,
		'msp' => 5060,
		'att' => 13,
		'def' => 999998,
		'lvl' => 50,
		'skill' => 33,
		'skills' => array('58'=>'0', '59'=>'0', '74'=>'0', '432'=>'0'),
		'money' => 3900,
		'arb' => '☾真篝火☽',
		'arbk' => 'DB',
		'arbe' => 500,
		'arbs' => 500,
		'arbsk' => 'aZ',
		'arh' => '☾真埋火☽',
		'arhk' => 'DH',
		'arhe' => 500,
		'arhs' => 500,
		'arhsk' => 'BZ',
		'ara' => '☾真残火☽',
		'arak' => 'DA',
		'arae' => 500,
		'aras' => 500,
		'arask' => 'bZ',
		'arf' => '☾真永火☽',
		'arfk' => 'DF',
		'arfe' => 500,
		'arfs' => 500,
		'arfsk' => 'MZ',
		'art' => '☾真焰火☽',
		'artk' => 'A',
		'arte' => 500,
		'arts' => 500,
		'artsk' => 'HZ',
		'sub' => array
		(
			0 => array
			(
				'name' => '✦繁花的烈火',
				'icon' => 'avatar_rek/fireseed.png',
				'wep' => '☾ΡΑΘΘЙΨΜЙΨΑП☾',
				'wepk' => 'WC',
				'wepe' => 233,
				'weps' => 9999,
				'wepsk' => 'z'
			),
		),
	);
	
	$skill983_boss_npc = array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'club' => 17,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 1,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'f',
		'pls' => 201,
		'mhp' => 8000,
		'msp' => 8000,
		'att' => 233,
		'def' => 9998,
		'lvl' => 200,
		'skill' => 777,
		'skills' => array('25'=>'0', '432'=>'0', '461'=>'1', '510'=>'2', '756'=>'1', '757'=>'0', '758'=>'0'),
		'money' => 1,
		'arb' => '☼篝火☼',
		'arbk' => 'DB',
		'arbe' => 3000,
		'arbs' => 3000,
		'arbsk' => 'aZ',
		'arh' => '☼埋火☼',
		'arhk' => 'DH',
		'arhe' => 3000,
		'arhs' => 3000,
		'arhsk' => 'AZ',
		'ara' => '☼残火☼',
		'arak' => 'DA',
		'arae' => 3000,
		'aras' => 3000,
		'arask' => 'hZ',
		'arf' => '☼永火☼',
		'arfk' => 'DF',
		'arfe' => 3000,
		'arfs' => 3000,
		'arfsk' => 'MZ',
		'art' => '☼焰火☼',
		'artk' => 'A',
		'arte' => 3000,
		'arts' => 3000,
		'artsk' => 'HZ',
		'sub' => array
		(
			0 => array
			(
				'name' => '大种火',
				'icon' => 'avatar_rek/fireseed2.png',
				'wep' => '梦境的碎片',
				'wepk' => 'WC',
				'wepe' => 2333,
				'weps' => 9999,
				'wepsk' => 'rfky',
				'itm1' => '『G.A.M.E.O.V.E.R』',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '',
			),
		),
	);
	
}
?>